_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
load_all_enabled_fonts: 1
enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=ABeeZee&subset=latin#italic'
  - 'https://www.google.com/webfonts/family?family=Alata&subset=vietnamese#regular'
  - 'https://www.google.com/webfonts/family?family=Alegreya&subset=latin#800'
  - 'https://www.google.com/webfonts/family?family=Abhaya Libre&subset=latin#500'
  - 'https://www.google.com/webfonts/family?family=Abril Fatface&subset=latin#regular'
load_on_themes: {  }
